apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.17.0.1:9090
    isDefault: true

  - name: Hevy
    type: frser-sqlite-datasource
    access: proxy
    database: /var/lib/grafana/hevy.db
